on: push
jobs:
  py-app:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python3 app.py
